//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChopChop.Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLoginDetail
    {
        public int DeviceLoginId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.Guid> DeviceToken { get; set; }
        public string DeviceType { get; set; }
        public string AppVersion { get; set; }
        public string OSVersion { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
