//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChopChop.Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItemModifiers = new HashSet<MenuItemModifier>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int MenuItemID { get; set; }
        public int MenuID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string ItemImagePath { get; set; }
        public Nullable<bool> SoldOut { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<MenuItemModifier> MenuItemModifiers { get; set; }
        public virtual VendorMenu VendorMenu { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
