//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChopChop.Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderRefunds = new HashSet<OrderRefund>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderDeliveryTime { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MasterOrderStatu MasterOrderStatu { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderRefund> OrderRefunds { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
