//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChopChop.Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUpOTP
    {
        public int ID { get; set; }
        public string MobileNumber { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
