//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChopChop.Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.OrderRefunds = new HashSet<OrderRefund>();
            this.Orders = new HashSet<Order>();
            this.RolesPermissions = new HashSet<RolesPermission>();
            this.UserFavoriteVendors = new HashSet<UserFavoriteVendor>();
            this.UserPrefrences = new HashSet<UserPrefrence>();
            this.UserSoldOutPreferences = new HashSet<UserSoldOutPreference>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string AccessToken { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string TimeZone { get; set; }
        public string ProfileImagePath { get; set; }
        public Nullable<System.Guid> DeviceToken { get; set; }
        public string DeviceType { get; set; }
        public string AppVersion { get; set; }
        public string OSVersion { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<OrderRefund> OrderRefunds { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<RolesPermission> RolesPermissions { get; set; }
        public virtual ICollection<UserFavoriteVendor> UserFavoriteVendors { get; set; }
        public virtual ICollection<UserPrefrence> UserPrefrences { get; set; }
        public virtual ICollection<UserSoldOutPreference> UserSoldOutPreferences { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
